name: rethinkdb_dart
version: 2.3.2+5
authors:
  - William Welch <billywelch@gmail.com>
  - Marcelo Henrique Neppel <marcelo.neppel@gmail.com>
description: Dart 2 driver for RethinkDB v2.3.
homepage: https://github.com/marceloneppel/rethinkdb
documentation: https://github.com/marceloneppel/rethinkdb
environment:
  sdk: ">=2.4.0 <3.0.0"
dependencies:
  protobuf: ^0.13.15
  crypto: ^2.0.6
  convert: ^2.1.1
  pbkdf2:
    git: "https://github.com/jamesots/pbkdf2"
dev_dependencies:
  test: ^1.6.5
  pedantic: ^1.8.0
