name: rethinkdb_driver
version: 0.7.0
author: William Welch <billywelch@gmail.com>
description: Dart driver for RethinkDB(v1.16).
homepage: https://github.com/billysometimes/rethinkdb
documentation: https://github.com/billysometimes/rethinkdb
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  protobuf: '>=0.3.3 <0.4.0'
  connection_pool: '>=0.1.0+2 <0.2.0'