name: rethinkdb_driver
version: 2.0.1-1
author: William Welch <billywelch@gmail.com>
description: Dart driver for RethinkDB.
homepage: https://github.com/billysometimes/rethinkdb
documentation: https://github.com/billysometimes/rethinkdb
dependencies:
  connection_pool: '>=0.1.0+2 <0.2.0'
  crypto: '>=0.9.0 <0.10.0'
  protobuf: '>=0.3.5 <0.4.0'
